version: '3'
services:
  common:
    build:
      context: ./common
      dockerfile: ./Dockerfile
    image: grpcmatt/common
  node-server:
    build:
      context: ./server/node
      dockerfile: ./Dockerfile
    depends_on:
      - common
    image: grpcmatt/node-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./envoy
      dockerfile: ./Dockerfile
    image: grpcmatt/envoy
    ports:
      - "8080:8080"
    links:
      - node-server
  js-client:
    build:
      context: ./client/js
      dockerfile: ./Dockerfile
    depends_on:
      - common
    image: grpcweb/js-client
    ports:
      - "8081:8081"
